CREATE TABLE "elims_item_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"discord_user_id" text NOT NULL,
	"discord_username" text NOT NULL,
	"torn_id" integer,
	"torn_name" text,
	"item_id" text NOT NULL,
	"item_name" text NOT NULL,
	"item_category" text NOT NULL,
	"quantity" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"is_test" boolean DEFAULT false NOT NULL,
	"reason" text,
	"request_message_id" text,
	"granting_message_id" text,
	"dm_sent" boolean DEFAULT false NOT NULL,
	"handled_by_discord_id" text,
	"handled_by_username" text,
	"handled_at" timestamp with time zone,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
