import {
	createMercContract,
	db,
	eq,
	getMercChannelConfig,
	getMercContractSummary,
	getMercContracts,
	getMercContractToken,
	guildConfigs,
	mapRowToMercContract,
	markMercContractTokenUsed,
	mercContracts,
} from "@sentinel/database";
import { notifyBotAction } from "@sentinel/utils/ipc";
import { Elysia, t } from "elysia";
import { resolveDiscordTornUser } from "../../lib/resolve-discord-torn-user";
import {
	requestMercClaimTarget,
	requestMercReleaseTarget,
} from "../../lib/scheduler-ipc";
import {
	getNextSubversiveUserKey,
	markSubversiveKeyDisabled,
	recordSubversiveKeySuccess,
} from "../../lib/subversive-key-pool";

interface ParsedWar {
	id: number;
	start: number;
	end: number | null;
	target: number;
	winner: number | null;
	factions: Array<{ id: number; name: string }>;
}

export const mercRoutes = new Elysia({ prefix: "/merc" })
	// ─── GET /v2/merc/contract-session ─────────────────────────────────────────
	.get(
		"/contract-session",
		async ({ query, set }) => {
			const tokenStr = query.token?.trim();
			if (!tokenStr) {
				set.status = 400;
				return { valid: false, error: "Missing session token." };
			}

			const tokenRow = await getMercContractToken(tokenStr);
			if (!tokenRow) {
				set.status = 404;
				return {
					valid: false,
					error: "Contract session not found or invalid.",
				};
			}

			if (tokenRow.used) {
				set.status = 410;
				return {
					valid: false,
					error: "This contract creation link has already been used.",
				};
			}

			if (new Date() > new Date(tokenRow.expiresAt)) {
				set.status = 410;
				return {
					valid: false,
					error: "This contract creation link has expired.",
				};
			}

			// Check if faction already has an active or upcoming contract
			const existingContracts = await getMercContracts(tokenRow.guildId);
			const activeContract = existingContracts.find(
				(c) =>
					c.factionId === tokenRow.factionId &&
					(c.status === "active" || c.status === "upcoming"),
			);
			if (activeContract) {
				return {
					valid: false,
					error: `Faction ${tokenRow.factionId} already has an active or upcoming contract in progress. The initial contract must end before a new contract can be created.`,
				};
			}

			const [gConfig] = await db
				.select({
					mercDefaultHitPrice: guildConfigs.mercDefaultHitPrice,
					mercDefaultStrickenHitPrice: guildConfigs.mercDefaultStrickenHitPrice,
				})
				.from(guildConfigs)
				.where(eq(guildConfigs.guildId, tokenRow.guildId));

			const standardHitPrice = gConfig?.mercDefaultHitPrice ?? 3000000;
			const strickenHitPrice = gConfig?.mercDefaultStrickenHitPrice ?? 4000000;

			return {
				valid: true,
				token: tokenRow.token,
				guildId: tokenRow.guildId,
				channelId: tokenRow.channelId,
				discordUserId: tokenRow.discordUserId,
				discordUsername: tokenRow.discordUsername,
				factionId: tokenRow.factionId,
				factionName: tokenRow.factionName,
				standardHitPrice,
				strickenHitPrice,
				expiresAt: tokenRow.expiresAt.toISOString(),
			};
		},
		{
			query: t.Object({
				token: t.String(),
			}),
			detail: {
				summary: "Validate Contract Creation Session Token",
				description:
					"Validates a single-use token generated by the Discord bot for client contract creation.",
			},
		},
	)

	// ─── GET /v2/merc/factions/validate ────────────────────────────────────────
	.get(
		"/factions/validate",
		async ({ query, set }) => {
			const tokenStr = query.token?.trim();
			const factionIdNum = Number.parseInt(query.factionId ?? "", 10);

			if (Number.isNaN(factionIdNum) || factionIdNum <= 0) {
				set.status = 400;
				return {
					valid: false,
					error: "Please provide a valid numeric Faction ID.",
				};
			}

			// Validate token if provided
			if (tokenStr) {
				const tokenRow = await getMercContractToken(tokenStr);
				if (
					!tokenRow ||
					tokenRow.used ||
					new Date() > new Date(tokenRow.expiresAt)
				) {
					set.status = 401;
					return {
						valid: false,
						error: "Invalid or expired contract session token.",
					};
				}
			}

			const keyObj = await getNextSubversiveUserKey();
			const apiKey = keyObj?.apiKey ?? process.env.TORN_API_KEY;

			if (!apiKey) {
				set.status = 503;
				return {
					valid: false,
					error: "No active Torn API key available in key pool or environment.",
				};
			}

			try {
				const tornUrl = new URL("https://api.torn.com/v2/faction");
				tornUrl.searchParams.set("id", String(factionIdNum));
				tornUrl.searchParams.set("selections", "basic,rankedwars");
				tornUrl.searchParams.set("key", apiKey);
				tornUrl.searchParams.set("comment", "SentinelMerc");

				const response = await fetch(tornUrl.toString(), {
					headers: { Authorization: `ApiKey ${apiKey}` },
					signal: AbortSignal.timeout(10_000),
				});

				if (!response.ok) {
					return {
						valid: false,
						error: `Torn API request failed with status ${response.status}`,
					};
				}

				const data = (await response.json()) as Record<string, unknown>;

				if (data.error && typeof data.error === "object") {
					const err = data.error as { code?: number; error?: string };
					if (
						keyObj &&
						(err.code === 2 || err.code === 13 || err.code === 10)
					) {
						markSubversiveKeyDisabled(keyObj.apiKey, err.code);
					}
					return {
						valid: false,
						error:
							err.error ?? "Failed to fetch faction information from Torn.",
					};
				}

				if (keyObj) {
					recordSubversiveKeySuccess(keyObj.apiKey);
				}

				const basic =
					(data.basic as Record<string, unknown> | undefined) ?? data;
				const factionName =
					typeof basic.name === "string" && basic.name
						? basic.name
						: `Faction ${factionIdNum}`;
				const tag = typeof basic.tag === "string" ? basic.tag : null;

				const parsedWars: ParsedWar[] = [];
				const rawRanked =
					data.rankedwars ??
					(data.wars as Record<string, unknown> | undefined)?.ranked ??
					data.warfareranked;

				if (Array.isArray(rawRanked)) {
					for (const item of rawRanked) {
						if (typeof item === "object" && item !== null) {
							const w = item as Record<string, unknown>;
							const id = Number(w.id ?? w.war_id ?? 0);
							const start = Number(w.start ?? 0);
							const end =
								w.end !== null && w.end !== undefined ? Number(w.end) : null;
							const target = Number(w.target ?? 0);
							const winner =
								w.winner !== null && w.winner !== undefined
									? Number(w.winner)
									: null;
							const facs = Array.isArray(w.factions)
								? (w.factions as Array<{ id: number; name: string }>)
								: [];
							parsedWars.push({
								id,
								start,
								end,
								target,
								winner,
								factions: facs,
							});
						}
					}
				} else if (typeof rawRanked === "object" && rawRanked !== null) {
					for (const [key, val] of Object.entries(rawRanked)) {
						if (typeof val === "object" && val !== null) {
							const v = val as Record<string, unknown>;
							const innerWar =
								(v.war as Record<string, unknown> | undefined) ?? v;
							const id = Number(innerWar.id ?? key);
							const start = Number(innerWar.start ?? 0);
							const end =
								innerWar.end !== null && innerWar.end !== undefined
									? Number(innerWar.end)
									: null;
							const target = Number(innerWar.target ?? 0);
							const winner =
								innerWar.winner !== null && innerWar.winner !== undefined
									? Number(innerWar.winner)
									: null;
							let facs: Array<{ id: number; name: string }> = [];
							if (Array.isArray(v.factions)) {
								facs = v.factions as Array<{ id: number; name: string }>;
							} else if (
								typeof v.factions === "object" &&
								v.factions !== null
							) {
								facs = Object.entries(v.factions).map(([fId, fObj]) => ({
									id: Number(fId),
									name:
										typeof (fObj as { name?: string }).name === "string"
											? (fObj as { name: string }).name
											: `Faction ${fId}`,
								}));
							}
							parsedWars.push({
								id,
								start,
								end,
								target,
								winner,
								factions: facs,
							});
						}
					}
				}

				const nowSec = Math.floor(Date.now() / 1000);
				const activeWar = parsedWars.find(
					(w) =>
						w.start <= nowSec &&
						(!w.end || w.end === 0 || w.end > nowSec) &&
						w.winner === null,
				);

				const upcomingWar = parsedWars
					.filter((w) => w.start > nowSec && w.winner === null)
					.sort((a, b) => a.start - b.start)[0];

				let warStatus: "no_war" | "upcoming" | "active" = "no_war";
				let chosenWar: ParsedWar | null = null;

				if (activeWar) {
					warStatus = "active";
					chosenWar = activeWar;
				} else if (upcomingWar) {
					warStatus = "upcoming";
					chosenWar = upcomingWar;
				}

				let opponent: { id: number; name: string } | null = null;
				if (chosenWar && Array.isArray(chosenWar.factions)) {
					const opp = chosenWar.factions.find((f) => f.id !== factionIdNum);
					if (opp) {
						opponent = { id: opp.id, name: opp.name };
					}
				}

				return {
					valid: true,
					id: factionIdNum,
					name: factionName,
					tag,
					warStatus,
					war: chosenWar
						? {
								id: chosenWar.id,
								start: chosenWar.start,
								end: chosenWar.end,
								target: chosenWar.target,
								opponent,
							}
						: null,
				};
			} catch (err) {
				return {
					valid: false,
					error:
						err instanceof Error
							? err.message
							: "Failed to validate faction war status.",
				};
			}
		},
		{
			query: t.Object({
				factionId: t.String(),
				token: t.Optional(t.String()),
			}),
			detail: {
				summary: "Validate Faction & Detect War Status (Client & Admin)",
				description:
					"Validates a Torn faction ID and detects live or upcoming ranked wars.",
			},
		},
	)

	// ─── POST /v2/merc/contracts/client ───────────────────────────────────────
	.post(
		"/contracts/client",
		async ({ body, set }) => {
			const tokenStr = body.token.trim();
			const tokenRow = await getMercContractToken(tokenStr);

			if (!tokenRow) {
				set.status = 404;
				return { error: "Contract session not found or invalid." };
			}

			if (tokenRow.used) {
				set.status = 410;
				return { error: "This contract creation link has already been used." };
			}

			if (new Date() > new Date(tokenRow.expiresAt)) {
				set.status = 410;
				return { error: "This contract creation link has expired." };
			}

			if (tokenRow.factionId !== body.factionId) {
				set.status = 403;
				return {
					error: `Session authorized for Faction ${tokenRow.factionId}, but submitted for Faction ${body.factionId}.`,
				};
			}

			// Guard: Initial contract has to end first before new contract can be created
			const existingContracts = await getMercContracts(tokenRow.guildId);
			const activeContract = existingContracts.find(
				(c) =>
					c.factionId === body.factionId &&
					(c.status === "active" || c.status === "upcoming"),
			);

			if (activeContract) {
				set.status = 409;
				return {
					error: `Faction ${body.factionId} already has an active or upcoming mercenary contract (ID: ${activeContract.id}). The initial contract must end before a new contract can be created.`,
				};
			}

			// Mark token used atomically
			await markMercContractTokenUsed(tokenStr);

			const [gConfig] = await db
				.select({
					mercRoleId: guildConfigs.mercRoleId,
					mercDefaultHitPrice: guildConfigs.mercDefaultHitPrice,
					mercDefaultStrickenHitPrice: guildConfigs.mercDefaultStrickenHitPrice,
				})
				.from(guildConfigs)
				.where(eq(guildConfigs.guildId, tokenRow.guildId));

			const effectiveHitPrice = gConfig?.mercDefaultHitPrice ?? 3000000;
			const effectiveStrickenPrice = body.terms.strickenHits
				? (gConfig?.mercDefaultStrickenHitPrice ?? 4000000)
				: null;

			const contract = await createMercContract(
				tokenRow.guildId,
				{
					factionId: body.factionId,
					factionName: body.factionName,
					warStatusAtCreation: body.warStatusAtCreation,
					warId: body.warId ?? null,
					warStart: body.warStart ?? null,
					warEnd: body.warEnd ?? null,
					warTarget: body.warTarget ?? null,
					warOpponent: body.warOpponent ?? null,
					startTime: body.startTime,
					startImmediately: body.startImmediately ?? false,
					startMinutesBeforeWar: body.startMinutesBeforeWar ?? null,
					endTime: body.endTime ?? null,
					endOnWarEnd: body.endOnWarEnd ?? false,
					terms: {
						...body.terms,
						idleDurationMinutes: body.terms.idleDurationMinutes ?? null,
					},
					hitPrice: effectiveHitPrice,
					strickenHitPrice: effectiveStrickenPrice,
					changeTermsOnWarStart: body.changeTermsOnWarStart ?? false,
					warStartTerms: body.warStartTerms
						? {
								...body.warStartTerms,
								idleDurationMinutes:
									body.warStartTerms.idleDurationMinutes ?? null,
							}
						: null,
					warStartHitPrice: body.warStartHitPrice ?? null,
					warStartStrickenHitPrice: body.warStartStrickenHitPrice ?? null,
					clientChannelId: tokenRow.channelId ?? null,
					clientDiscordId: tokenRow.discordUserId,
				},
				`Client (${tokenRow.discordUsername ?? tokenRow.discordUserId})`,
			);

			// Post announcement to upcoming contracts channel
			const channelConfig = await getMercChannelConfig(tokenRow.guildId);

			if (channelConfig.upcomingContracts) {
				void notifyBotAction("post_merc_contract_announcement", {
					guildId: tokenRow.guildId,
					channelName: channelConfig.upcomingContracts,
					contract,
					mercRoleId: gConfig?.mercRoleId ?? null,
				});
			}

			// Also post announcement embed to client's private channel without role ping
			if (tokenRow.channelId) {
				void notifyBotAction("post_merc_contract_announcement", {
					guildId: tokenRow.guildId,
					channelName: tokenRow.channelId,
					contract,
					mercRoleId: null, // Zero ping in private client channel
				});
			}

			const baseUrl =
				process.env.DASHBOARD_URL ||
				(process.env.NODE_ENV === "production"
					? "https://dashboard.blasted-labs.tech"
					: "http://localhost:3000");

			const receiptUrl = `${baseUrl}/#/merc/receipt/${contract.id}`;

			return {
				success: true,
				contractId: contract.id,
				receiptUrl,
				contract,
			};
		},
		{
			body: t.Object({
				token: t.String(),
				factionId: t.Number(),
				factionName: t.String(),
				warStatusAtCreation: t.Union([
					t.Literal("no_war"),
					t.Literal("upcoming"),
					t.Literal("active"),
				]),
				warId: t.Optional(t.Nullable(t.Number())),
				warStart: t.Optional(t.Nullable(t.Number())),
				warEnd: t.Optional(t.Nullable(t.Number())),
				warTarget: t.Optional(t.Nullable(t.Number())),
				warOpponent: t.Optional(
					t.Nullable(
						t.Object({
							id: t.Number(),
							name: t.String(),
						}),
					),
				),
				startTime: t.String(),
				startImmediately: t.Optional(t.Boolean()),
				startMinutesBeforeWar: t.Optional(t.Nullable(t.Number())),
				endTime: t.Optional(t.Nullable(t.String())),
				endOnWarEnd: t.Optional(t.Boolean()),
				terms: t.Object({
					statuses: t.Object({
						online: t.Boolean(),
						idle: t.Boolean(),
						offline: t.Boolean(),
					}),
					idleDurationMinutes: t.Optional(t.Nullable(t.Number())),
					strickenHits: t.Boolean(),
					levelRange: t.Tuple([t.Number(), t.Number()]),
				}),
				hitPrice: t.Optional(t.Number()),
				strickenHitPrice: t.Optional(t.Nullable(t.Number())),
				changeTermsOnWarStart: t.Optional(t.Boolean()),
				warStartTerms: t.Optional(
					t.Nullable(
						t.Object({
							statuses: t.Object({
								online: t.Boolean(),
								idle: t.Boolean(),
								offline: t.Boolean(),
							}),
							idleDurationMinutes: t.Optional(t.Nullable(t.Number())),
							strickenHits: t.Boolean(),
							levelRange: t.Tuple([t.Number(), t.Number()]),
						}),
					),
				),
				warStartHitPrice: t.Optional(t.Nullable(t.Number())),
				warStartStrickenHitPrice: t.Optional(t.Nullable(t.Number())),
			}),
			detail: {
				summary: "Create Mercenary Contract (Client Tokenized Submission)",
				description:
					"Submits a new contract via client token, links the private channel, and announces it.",
			},
		},
	)

	// ─── GET /v2/merc/contracts/:contractId/receipt ───────────────────────────
	.get(
		"/contracts/:contractId/receipt",
		async ({ params, set }) => {
			const [row] = await db
				.select()
				.from(mercContracts)
				.where(eq(mercContracts.id, params.contractId));

			if (!row) {
				set.status = 404;
				return { error: "Contract receipt not found." };
			}

			const contract = mapRowToMercContract(row);
			const summary = await getMercContractSummary(params.contractId);

			// Enrich target breakdown with hit prices for client transparent accounting
			const targetsWithCost = summary.targetBreakdown.map((target) => {
				const standardCost =
					target.standardHitsReceived * (contract.hitPrice ?? 0);
				const strickenRate =
					contract.strickenHitPrice ?? contract.hitPrice ?? 0;
				const strickenCost = target.strickenHitsReceived * strickenRate;
				return {
					...target,
					standardRate: contract.hitPrice,
					strickenRate,
					totalCost: standardCost + strickenCost,
				};
			});

			return {
				contract: {
					id: contract.id,
					guildId: contract.guildId,
					factionId: contract.factionId,
					factionName: contract.factionName,
					warStatusAtCreation: contract.warStatusAtCreation,
					warOpponent: contract.warOpponent,
					startTime: contract.startTime,
					endTime: contract.endTime,
					status: contract.status,
					hitPrice: contract.hitPrice,
					strickenHitPrice: contract.strickenHitPrice,
					createdAt: contract.createdAt,
				},
				summary: {
					totalHits: summary.totalHits,
					totalPayout: summary.totalPayout,
					participatingMercsCount: summary.mercPayouts.length,
					targetsHitCount: summary.targetBreakdown.length,
					targetBreakdown: targetsWithCost,
				},
			};
		},
		{
			params: t.Object({
				contractId: t.String(),
			}),
			detail: {
				summary: "Client Contract Receipt Viewer",
				description:
					"Provides unauthenticated breakdown of contract targets hit, counts, and costs for clients.",
			},
		},
	)

	// ─── POST /v2/merc/targets/claim-discord ──────────────────────────────────
	.post(
		"/targets/claim-discord",
		async ({ body, set }) => {
			const resolved = await resolveDiscordTornUser(body.discordUserId);

			const result = await requestMercClaimTarget(
				body.contractId,
				body.targetId,
				{
					discordId: body.discordUserId,
					discordTag: body.discordUsername,
					tornId: resolved?.tornId,
					tornName: resolved?.tornName,
				},
			);

			if (!result.success) {
				set.status = 400;
				return { error: result.reason ?? "Failed to claim mercenary target" };
			}

			return { success: true };
		},
		{
			body: t.Object({
				contractId: t.String(),
				targetId: t.Number(),
				discordUserId: t.String(),
				discordUsername: t.String(),
			}),
			detail: {
				summary: "Claim Mercenary Target (Discord)",
				description:
					"Claims a mercenary target via Discord interactive button click.",
			},
		},
	)

	// ─── POST /v2/merc/targets/release-discord ────────────────────────────────
	.post(
		"/targets/release-discord",
		async ({ body, set }) => {
			const result = await requestMercReleaseTarget(
				body.contractId,
				body.targetId,
				body.discordUserId,
			);

			if (!result.success) {
				set.status = 400;
				return { error: result.reason ?? "Failed to release target" };
			}

			return { success: true };
		},
		{
			body: t.Object({
				contractId: t.String(),
				targetId: t.Number(),
				discordUserId: t.String(),
			}),
			detail: {
				summary: "Release Mercenary Target (Discord)",
				description:
					"Releases a claimed mercenary target via Discord interactive button click.",
			},
		},
	);
