export const STORAGE = {
	apiUrl: "satf_api_url",
	token: "satf_auth_token",
	user: "satf_user_data",
	position: "satf_launcher_position",
	panelOpen: "satf_panel_open",
	persistOpen: "satf_persist_open",
	activeTab: "satf_active_tab",
	minFFThreshold: "satf_min_ff_threshold",
	maxFFThreshold: "satf_max_ff_threshold",
	maxBSThreshold: "satf_max_bs_threshold",
	cachedTargets: "satf_cached_targets",
	directAttack: "satf_direct_attack",
	hideHighFF: "satf_hide_high_ff",
	hideHighBS: "satf_hide_high_bs",
	targetSortBy: "satf_target_sort_by",
	targetSortOrder: "satf_target_sort_order",
	ignoredTargets: "satf_ignored_targets",
	currentTarget: "satf_current_target",
	warOpponentIds: "satf_war_opponent_ids",
	warState: "satf_war_state",
	cachedBounties: "satf_cached_bounties",
	warSubTab: "satf_war_sub_tab",
	bountyMinReward: "satf_bounty_min_reward",
	bountyMaxReward: "satf_bounty_max_reward",
	disableHud: "satf_disable_hud",
} as const;

export const DEFAULTS = {
	apiUrl: "https://subversive.blasted-labs.tech",
	minFFThreshold: 1.2,
	maxFFThreshold: 3.0,
	maxBSThreshold: 5e9,
	bountyMinReward: 0,
	bountyMaxReward: 0,
	directAttack: true,
	disableHud: false,
	persistOpen: false,
} as const;
